#ifndef __IO_DEFINES_H__
#define __IO_DEFINES_H__

#define SELECT_INPUT    EPOLLIN
#define SELECT_OUTPUT   EPOLLOUT
#define SELECT_HANGUP   EPOLLHUP
#define SELECT_ERROR    EPOLLERR
#define SELECT_ONESHOT  EPOLLONESHOT

#define SELECT_MAX_FD_SIZE (1024)
#define SELECT_CHECK_FD_INTERVALS (2)

#endif
